version: '2'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - /root/mysql_website:/var/lib/mysql
  web:
    build: .
    env_file:
      - '.env.web'
    entrypoint: /myapp/rails-entrypoint.sh
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
